In [ ]:
#importing
import numpy as np

Array

In [ ]:
#creating 1D array
a=np.array([2,3,4,5])
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
#creating 2D array
b=np.array([[2,3,4],[7,8,9]])
print(b)

[[2 3 4]
 [7 8 9]]


In [ ]:
#creatingna 3D array   rows colums groups
c=np.array([[[2,3,4],[6,7,8]],[[6,9,0],[2,3,4]]])
print(c)

[[[2 3 4]
  [6 7 8]]

 [[6 9 0]
  [2 3 4]]]


In [ ]:
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


In [ ]:
#ones
d=np.ones((2,3,4))
print(d)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [ ]:
#ones
e=np.ones((3,2))
print(e)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#zeros
f = np.eye((4))
print(f)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
f=np.zeros((3,2))
print(f)


[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
g=np.zeros((4,3))
print(g)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#arrays

h = np.arange(3,31,3)
print(h)

[ 3  6  9 12 15 18 21 24 27 30]


In [ ]:
#arange with reshape
p=np.arange(3,31,3).reshape(5,2)
print(p)

[[ 3  6]
 [ 9 12]
 [15 18]
 [21 24]
 [27 30]]


In [ ]:
s=np.arange(5,1001,5)
print(s)

[   5   10   15   20   25   30   35   40   45   50   55   60   65   70
   75   80   85   90   95  100  105  110  115  120  125  130  135  140
  145  150  155  160  165  170  175  180  185  190  195  200  205  210
  215  220  225  230  235  240  245  250  255  260  265  270  275  280
  285  290  295  300  305  310  315  320  325  330  335  340  345  350
  355  360  365  370  375  380  385  390  395  400  405  410  415  420
  425  430  435  440  445  450  455  460  465  470  475  480  485  490
  495  500  505  510  515  520  525  530  535  540  545  550  555  560
  565  570  575  580  585  590  595  600  605  610  615  620  625  630
  635  640  645  650  655  660  665  670  675  680  685  690  695  700
  705  710  715  720  725  730  735  740  745  750  755  760  765  770
  775  780  785  790  795  800  805  810  815  820  825  830  835  840
  845  850  855  860  865  870  875  880  885  890  895  900  905  910
  915  920  925  930  935  940  945  950  955  960  965  970  975  980
  985 

In [ ]:
q=np.linspace(11,24,10)
print(q)

[11.         12.44444444 13.88888889 15.33333333 16.77777778 18.22222222
 19.66666667 21.11111111 22.55555556 24.        ]


In [ ]:
o=np.arange(1,7).reshape(2,3)
print(o)
l=np.arange(9,15).reshape(2,3)
print(l)

[[1 2 3]
 [4 5 6]]
[[ 9 10 11]
 [12 13 14]]


In [ ]:
#sum of arrays
print(o+l)

[[10 12 14]
 [16 18 20]]


In [ ]:
#sum function
u=np.sum(o+l)
print(u)

90


In [ ]:
#sum function using axis=0
r=np.sum((o,l),axis=0)
print(r)

[[10 12 14]
 [16 18 20]]


In [ ]:
#sum function using axis=1
m=np.sum((o,l),axis=1)
print(m)

[[ 5  7  9]
 [21 23 25]]


In [ ]:
n=np.ones((4,2))
e=np.ones((4,2))
print(np.sum((n,e),axis=0))
print(np.sum((n,e),axis=1))

[[2. 2.]
 [2. 2.]
 [2. 2.]
 [2. 2.]]
[[4. 4.]
 [4. 4.]]


In [ ]:
A=np.array([[1,1],[0,1]])
B=np.array([[2,0],[3,4]])
print(A*B)
print(A@B)


[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


b=np.array[25,239,361,81]#find square roots and

---

iterate through result values output 5 square is 25..

In [ ]:
B=np.array( [25,289,361,81])
for i in B:
  print(int(np.sqrt(i)),"square is",i)

5 square is 25
17 square is 289
19 square is 361
9 square is 81


In [ ]:
Q= np.array([34,35,36,37,38,39])
Q.resize(2,3)
B=np.array([4,5,6,7,8,9])
B.resize(2,3)
print(np.vstack((Q,B)))
print("\n")
print(np.hstack(Q))

[[34 35 36]
 [37 38 39]
 [ 4  5  6]
 [ 7  8  9]]


[34 35 36 37 38 39]


In [ ]:
a=np.arange(30).reshape(2,3,5)
print(a)
print("output of dstack")
print(np.dstack(a))


[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
output of dstack
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("/content/demodt.txt")

In [ ]:
df

State  Literacy  Cleanliness  Crime_Rate  Good
0      A        92           90          54     0
1      B        56           67          50     1
2      C        78           85          62     0
3      D        63           72          48     1
4      E        85           79          55     0
5      F        71           68          58     0
6      G        80           83          51     0
7      H        67           74          47     1
8      I        89           88          53     0
9      J        58           65          49     1
10     K        82           81          60     0
11     L        75           78          57     0
12     M        69           70          46     1
13     N        87           86          52     0
14     O        61           63          45     1
15     P        93           91          56     0
16     Q        55           66          61     0
17     R        76           77          59     0
18     S        84           82          44     1
19     T        70           69          50     1
20     U        94           92          57     0
21     V        59           64          52     0
22     W        83           80          43     1
23     X        74           76          63     0
24     Y        68           73          41     1
25     Z        88           84          47     1

In [ ]:
import sklearn.tree