In [ ]:
import numpy as np
#RANDOM MODULE IS SUB-PACAKAGE OF NUMPY

In [ ]:
A=np.random.rand(1)
print(A)

[0.09205269]


In [ ]:
A=np.random.rand(8,4)#rand-rang is between 0 and 1
print(A)

[[0.35850009 0.7867703  0.92920641 0.98227131]
 [0.90181479 0.2854737  0.36674977 0.83053767]
 [0.79374435 0.44906037 0.02505708 0.9045614 ]
 [0.44199637 0.87987114 0.41261359 0.81493855]
 [0.00112898 0.2139473  0.91646615 0.88616841]
 [0.6350296  0.41328927 0.79351477 0.57134929]
 [0.49372249 0.53597086 0.07004514 0.16039567]
 [0.59234816 0.4724852  0.00291045 0.8630751 ]]


In [ ]:
A=10*np.random.rand(8,4)
print(A)


[[2.80881719 5.73785884 7.28159008 6.23401042]
 [1.17903001 0.48205883 8.67905033 8.07546905]
 [6.40212302 9.19672908 6.42435376 7.77158972]
 [0.95165548 1.23748302 2.96516301 7.3873566 ]
 [9.21375239 7.88991631 1.1278642  8.67937618]
 [5.6681812  0.87785017 2.9203397  9.99573643]
 [1.20881142 3.06746798 3.98696636 8.06630285]
 [5.88794225 1.83577008 2.48244026 5.25154428]]


In [ ]:
A=np.floor(10*np.random.rand(8,4))
print(A)

[[1. 4. 8. 0.]
 [7. 0. 4. 8.]
 [0. 6. 4. 9.]
 [8. 8. 5. 1.]
 [7. 8. 3. 8.]
 [9. 9. 6. 0.]
 [8. 1. 1. 3.]
 [7. 0. 6. 8.]]


In [ ]:
A=np.arange(1,33).reshape(8,4)
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [ ]:
print(np.vsplit(A,4))  #here 4 is the no of splits we require

[array([[1., 4., 8., 0.],
       [7., 0., 4., 8.]]), array([[0., 6., 4., 9.],
       [8., 8., 5., 1.]]), array([[7., 8., 3., 8.],
       [9., 9., 6., 0.]]), array([[8., 1., 1., 3.],
       [7., 0., 6., 8.]])]


In [ ]:
np.vsplit(A,(3,5))#split it after 3rd row and 5th row

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20]]),
 array([[21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [ ]:
A=np.random.rand(4,8)#rand-rang is between 0 and 1
print(A)

[[0.42447307 0.69850996 0.45883675 0.56184631 0.45686942 0.92314281
  0.5279794  0.62002302]
 [0.5124866  0.04898422 0.00474511 0.13366809 0.24397386 0.8395131
  0.16037014 0.37201602]
 [0.09360614 0.03615251 0.45312533 0.5181065  0.25137862 0.39681149
  0.49928987 0.51639376]
 [0.90515876 0.41591699 0.56666323 0.97155274 0.95039958 0.30796885
  0.07653942 0.15380024]]


In [ ]:
A=np.arange(1,33).reshape(4,8)
print(A)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]]


In [ ]:
#np.vsplit(A,(3,5))#split it after 3rd row and 5th row

In [ ]:
np.hsplit(A,4)#split it after 3rd row and 5th row
#spliting takes place from left to right
#split divide the array into 4 parts


[array([[ 1,  2],
        [ 9, 10],
        [17, 18],
        [25, 26]]),
 array([[ 3,  4],
        [11, 12],
        [19, 20],
        [27, 28]]),
 array([[ 5,  6],
        [13, 14],
        [21, 22],
        [29, 30]]),
 array([[ 7,  8],
        [15, 16],
        [23, 24],
        [31, 32]])]

In [ ]:
np.hsplit(A,(3,7))

[array([[ 1,  2,  3],
        [ 9, 10, 11],
        [17, 18, 19],
        [25, 26, 27]]),
 array([[ 4,  5,  6,  7],
        [12, 13, 14, 15],
        [20, 21, 22, 23],
        [28, 29, 30, 31]]),
 array([[ 8],
        [16],
        [24],
        [32]])]

In [ ]:
np.hsplit(A,(2,5)) #split takes place after 2nd column and 5th column


[array([[ 1,  2],
        [ 9, 10],
        [17, 18],
        [25, 26]]),
 array([[ 3,  4,  5],
        [11, 12, 13],
        [19, 20, 21],
        [27, 28, 29]]),
 array([[ 6,  7,  8],
        [14, 15, 16],
        [22, 23, 24],
        [30, 31, 32]])]

# Trignometry

In [ ]:
np.pi

3.141592653589793

In [ ]:
B=[np.pi/4,np.pi/3,np.pi/2,np.pi]
print(A)

[0.7853981633974483, 1.0471975511965976, 1.5707963267948966, 3.141592653589793]


In [ ]:
c=np.rad2deg(B)
print(c)#convert radians to degrees

[ 45.  60.  90. 180.]


In [ ]:
D=np.deg2rad(c)#convert degree to radians
print(D)


[ 45.  60.  90. 180.]
[0.78539816 1.04719755 1.57079633 3.14159265]


In [ ]:
np.sin(1) #radians

0.8414709848078965

In [ ]:
np.cos(1)

0.5403023058681398

In [ ]:
np.tan(1)

1.5574077246549023

### **statistics**

In [ ]:
st=np.array([23,34,45,56,67,78,89,90])
np.mean(st)


60.25

In [ ]:
np.median(st)


61.5

In [ ]:
np.var(st)


549.9375

In [ ]:
np.std(st)#np.sqrt(np.var(st))

23.450746256782534

std=sqrt(sigma(x1-x_)**2/n)


x1 is each element
x_ is mean

var=std**2

In [ ]:
c=np.arange(1,5).reshape(2,2)
print(c)

[[1 2]
 [3 4]]


In [ ]:
#logic for inverse matrix
np.linalg.inv(c)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
c=10*np.random.rand(24).reshape(6,4)
print(c)

[[0.74221094 6.84838284 3.75276878 8.27784965]
 [5.9541356  8.07552454 6.21809053 0.8446456 ]
 [0.79358351 9.78411998 0.01208055 4.68225748]
 [6.62515255 1.21181537 1.47751365 7.93338435]
 [0.69976968 3.31007242 2.6772674  3.49815064]
 [0.39882727 6.34490081 3.84484703 6.63353726]]


In [ ]:
print(np.argmax(c))

9


In [ ]:
C=np.floor(10*np.random.rand(24)).reshape(6,4)
print(C)


[[5. 7. 0. 8.]
 [8. 8. 9. 8.]
 [8. 8. 7. 1.]
 [7. 0. 9. 7.]
 [2. 8. 9. 0.]
 [1. 5. 6. 4.]]


In [ ]:
c=np.floor(10*np.random.rand(6,4))
print(c)

[[6. 2. 0. 0.]
 [6. 4. 6. 1.]
 [1. 9. 9. 1.]
 [7. 6. 2. 7.]
 [4. 7. 4. 2.]
 [1. 5. 9. 6.]]


In [ ]:
print(np.argmax(c))

9


In [ ]:

print(np.argmax(c,axis=1))
print(np.argmax(c,axis=0))

[3 1 1 3 3 3]
[3 2 1 0]


In [ ]:
print(c)
print(np.argmin(c))

[[6. 2. 0. 0.]
 [6. 4. 6. 1.]
 [1. 9. 9. 1.]
 [7. 6. 2. 7.]
 [4. 7. 4. 2.]
 [1. 5. 9. 6.]]
2


In [ ]:
print(np.argmin(c,axis=0))
print(np.argmin(c,axis=1))

[2 0 0 0]
[2 3 0 2 3 0]


searching

In [ ]:
a=np.array([34,45,6,17,88,91])
#output=(0,1,4)
print(np.where(a%2==0))
print(np.where(a%2==1))
#(array([0,1,4],dtype=int64),)


(array([0, 2, 4]),)
(array([1, 3, 5]),)


In [ ]:
a=np.array([6,7,8,54,60])
print(np.where(a%6==0))

(array([0, 3, 4]),)


In [ ]:
a=np.array([2,4,7,3,6]) #searchsort
x=np.searchsorted(a,3)
print(x)


1


In [ ]:
x=np.searchsorted(a,10)
print(x)

5


In [ ]:
a=np.array([2,4,6,7,8])
x=np.searchsorted(a,7)
print(x)

3


In [ ]:
a=np.array(['banana','apple','cherry']) #sorting
print(np.sort(a))

['apple' 'banana' 'cherry']


In [ ]:
a=np.array(['true','false','true'])
print(np.sort(a))


['false' 'true' 'true']


In [ ]:
arr=np.array([[3,2,4],[5,0,1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [ ]:
arr=np.array([2,534,32,24,64,66])
x=[True,False,True,False,True,True]
newarr=arr[x]
print(newarr)

[ 2 32 64 66]


filtering

In [ ]:
arr=np.array([40,45,56,78,98,21])
filt=np.where(arr%2==0)
print(filt)

(array([0, 2, 3, 4]),)


In [ ]:
arr[filt]

array([40, 56, 78, 98])

In [ ]:
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])

40
45
56
78


In [ ]:
a=np.array(["Vamsi", "Naga", "Sai","Jaya","Kanth"])
initials=np.array(["A","B","C","D","E"])
for i,j in zip(initials,a):
  print(i,".",j)

A . Vamsi
B . Naga
C . Sai
D . Jaya
E . Kanth


In [ ]:
a1=np.array([10,20,30,40,50,60])
a2=np.array([20,21,22,23,24,25])
n=np.multiply(a1,a2)
print(n)

[ 200  420  660  920 1200 1500]


In [ ]:
a1=np.array([10,20,30,40,50,60])
a2=np.array([20,21,22,23,24,25])
n=np.divide(a1,a2)
print(n)

[0.5        0.95238095 1.36363636 1.73913043 2.08333333 2.4       ]


In [ ]:
a1=np.array([10,20,30,40,50,60])
a2=np.array([20,21,22,23,24,25])
n=np.mod(a1,a2)
print(n)

[10 20  8 17  2 10]


In [ ]:
a1=np.array([10,20,30,40,50,60])
a2=np.array([20,21,22,23,24,25])
n=np.divmod(a1,a2)
print(n)

(array([0, 0, 1, 1, 2, 2]), array([10, 20,  8, 17,  2, 10]))


logrithams

In [ ]:
a1=np.arange(1,10)
print(a1)
print(np.log10(a1))

[1 2 3 4 5 6 7 8 9]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


In [ ]:
a2=22
print(np.log10(a2))

1.3424226808222062


In [ ]:
a2=np.array([5,6,8,10])
x=np.cumprod(a2)
print(x)

[   5   30  240 2400]


In [ ]:
a1=np.array([10,15,25,33])
newarr=np.diff(a1)
print(newarr)

[ 5 10  8]


In [ ]:
num1=455
num2=665
x=np.lcm(num1,num2)
print(x)

8645


In [ ]:
num1=35
num1=2345
x=np.gcd(num1,num2)
print(x)

35


In [ ]:
a=np.array([12,15,60])
gc=np.gcd.reduce(a)#it takes multiple inputs given single output
print(gc)

3


In [ ]:
a=np.array([12,5,6])
lc=np.gcd.reduce(a)#it takes multiple inputs given single output
print(lc)

1
